services:
    langchain_service:
        build:
            context: ./src/backend
            dockerfile: docker/Dockerfile
        container_name: api_langchain
        restart: on-failure
        volumes:
        - ${USERPROFILE}/.cache/huggingface:/root/.cache/huggingface
        - ${USERPROFILE}/.cache/torch:/root/.cache/torch
        
        shm_size: 512m
        ports:
            - 8003:8003
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

