FROM python:3.11-slim

WORKDIR /backend

COPY requirements.txt .

RUN pip install --upgrade wheel setuptools pip \
    && pip install -r requirements.txt --no-cache-dir

COPY . .

EXPOSE 8003

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003"]


